@startuml
left to right direction

:Developer:
:Product Owner: as PO
:Requirements Engineer: as RE
:Software Architect: as Architect
:Quality Manager: as QM

package Features {
(Describing a feature) as NewFeature #yellow
(Implementing feature) as FeatureImplementation #yellow
(Fetching a feature report) as Report
(Planning a feature go-live) as GoLive
(Collaborating on a feature) as CollabFeature
(Testing a feature) as Testing
(Completing a feature) as CompleteFeature
}

package Tasks {
(Creating a task) as NewTask #yellow
(Adding progress to a task) as Progress
(Marking a task as blocked) as Blocked #yellow
(Tackling blocking issues) as Tackling
(Collaborating on a task) as CollabTask
(Completing a task) as CompleteTask
}

package Interfaces {
(Describing an interface) as NewInterface
}

package Services {
(Describing a service) as NewService
}

package SolutionDesigns {
(Describing architecture) as NewSolutionDesign
}

package Tests {
(Describing a test) as NewTest
(Linked to feature/task/interface) as LinkTest
(Marked as executable) as ExecutableTest
(Executing tests) as TestExecuted
}

package SoftFeatures {
(Starting a discussion) as Discussion
(Giving feedback) as Feedback
(Tracking impediments) as Impediment
(Making proposals/opinions) as Opinion
(Tracking decisions) as Decision
(Recording conflicts) as Conflict
note bottom of SoftFeatures : To be defined
}

RE --> NewFeature
Architect --> NewFeature
PO --> NewFeature

Developer --> FeatureImplementation
Developer --> NewTask
Architect --> NewTask

Developer --> Progress

Developer --> Blocked

PO --> Report

Architect --> Tackling

Architect --> GoLive
PO --> GoLive

Architect --> NewInterface
Developer --> NewInterface

Architect --> NewService
Developer --> NewService

Architect --> NewSolutionDesign

RE --> CollabFeature
Architect --> CollabFeature
PO --> CollabFeature

Architect --> CollabTask
Developer --> CollabTask

QM --> Testing

QM --> NewTest
QM --> LinkTest
Developer --> ExecutableTest
QM --> TestExecuted

QM --> CompleteTask
QM --> CompleteFeature

legend
  | <#yellow>yellow  | Use case implemented |
  | <#orange>orange | Use case in progress |
end legend

@enduml
