@startuml
left to right direction

:Developer:
:Product Owner: as PO
:Requirements Engineer: as RE
:Software Architect: as Architect
:Quality Manager: as QM

package Features {
(Describing a feature) as NewFeature #yellow
(Implementing feature) as FeatureImplementation #yellow
(Fetching a feature report) as Report
(Planning a feature go-live) as GoLive
(Collaborating on a feature) as CollabFeature
(Testing a feature) as Testing
}

package Tasks {
(Creating a task) as NewTask #yellow
(Adding progress to a task) as Progress
(Marking a task as blocked) as Blocked #yellow
(Tackling blocking issues) as Tackling
(Collaborating on a task) as CollabTask
}
package Interfaces {
(Describing interfaces) as NewInterface
}

RE --> NewFeature
Architect --> NewFeature
PO --> NewFeature

Developer --> FeatureImplementation
Developer --> NewTask
Architect --> NewTask

Developer --> Progress

Developer --> Blocked

PO --> Report

Architect --> Tackling

Architect --> GoLive
PO --> GoLive

Architect --> NewInterface
Developer --> NewInterface

RE --> CollabFeature
Architect --> CollabFeature
PO --> CollabFeature

Architect --> CollabTask
Developer --> CollabTask

QM --> Testing

legend
  | <#yellow>yellow  | Use case implemented |
  | <#orange>orange | Use case in progress |
end legend

@enduml
